apiVersion: v1
kind: Service
metadata:
  name: mpm-api-service
spec:
  selector:
    app: mpm-api
  ports:
  - protocol: "TCP"
    port: 4000
    targetPort: 4000
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mpm-api
spec:
  selector:
    matchLabels:
      app: mpm-api
  replicas: 1
  template:
    metadata:
      labels:
        app: mpm-api
    spec:
      volumes:
      - name: local-pv
        persistentVolumeClaim:
          claimName: local-pvc
      containers:
      - name: mpm-api
        image: mraylex/mpm_api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
        volumeMounts:
        - mountPath: /mnt/data
          name: local-pv