kind: Pod
metadata:
  name: hello-world-1
spec:  # specification of the pod’s contents
  restartPolicy: Never
  containers:
  - name: hello
    image: "ubuntu:14.04"
    env:
    - name: MESSAGE
      value: "hello world"
      command: [ "python" ]
      args: [ "./main.py", "1" ]
---
kind: Pod
metadata:
  name: hello-world-2
spec:  # specification of the pod’s contents
  restartPolicy: Never
  containers:
  - name: hello
    image: "ubuntu:14.04"
    env:
    - name: MESSAGE
      value: "hello world"
      command: [ "python" ]
      args: [ "./main2.py", "2" ]
---
kind: Pod
metadata:
  name: hello-world-3
spec:  # specification of the pod’s contents
  restartPolicy: Never
  containers:
  - name: hello
    image: "ubuntu:14.04"
    env:
    - name: MESSAGE
      value: "hello world"
      command: [ "python" ]
      args: [ "./main3.py", "3" ]