apiVersion: v1
kind: Service
metadata:
  name: web-service-api1
spec:
  type: NodePort
  selector:
    app: api1
  ports:
  - protocol: "TCP"
    port: 4000
    targetPort: 4000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api1
spec:
  selector:
    matchLabels:
      app: api1
  replicas: 1
  template:
    metadata:
      labels:
        app: api1
    spec:
      volumes:
      - name: my-volume
        persistentVolumeClaim:
          claimName: my-pvc
      containers:
      - name: api1
        image: mraylex/api1:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
        volumeMounts:
        - mountPath: /path/data/
          name: my-volume

---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: api1-ingress
#  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /
#spec:
#    rules:
#      - http:
#          paths:
#          - path: /api1
#            pathType: Prefix
#            backend:
#              service:
#                name: web-service-api1
#                port:
#                  number: 80
