apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  #serviceAccountName: default
  volumes:
    - name: my-volume
      persistentVolumeClaim:
        claimName: my-pvc
  containers:
  - name: test
    image: mraylex/test-python:latest
    ports:
    - containerPort: 80
    volumeMounts:
      - mountPath: /path/data/
        name: my-volume