kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: allow-post-role-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: ClusterRole
  name: allow-post-role
  apiGroup: rbac.authorization.k8s.io

